{% set ver = "1.5.0" %}
{% set beta = "beta20161122" %}
{% set version = ver + "_" + beta %}

package:
  name: pyngl
  version: {{ version }}

source:
  fn: pyngl-{{ version }}.tar.gz
  url: https://github.com/NCAR/pyngl/archive/{{ version }}.tar.gz
  sha256: 5b13af17d819d210e92d179a73f1323bc0feeeafefe55ded043b74462ebf712d
  patches:
    - beta_version.patch

build:
  number: 2
  skip: True  # [win or py3k]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - ncl
    - gcc
    - python
    - numpy x.x
    - libpng >=1.6.28,<1.7
    - pkg-config
    - fontconfig 2.12.*
    - freetype 2.7|2.7.*
    - expat
    - cairo 1.14.*
    - zlib 1.2.*
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
  run:
    - ncl
    - libgcc
    - python
    - numpy x.x
    - libpng >=1.6.28,<1.7
    - pkg-config
    - fontconfig 2.12.*
    - freetype 2.7|2.7.*
    - expat
    - cairo 1.14.*
    - zlib 1.2.*
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender

test:
  source_files:
    - src/examples
  requires:
    - nose
  imports:
    - Ngl
  commands:
    - cd src/examples && for file in xy2.py; do echo $file ; nosetests $file ; done | tee pyngl-test.log

about:
  home: http://pyngl.ucar.edu/
  license: 'PyNGL Source Code'
  summary: 'PyNGL is a scientific data visualization package with an emphasis on high quality 2D visualizations.'

extra:
  recipe-maintainers:
    - khallock
    - marylhaley
    - david-ian-brown
