{% set version = "1.6.1" %}

package:
  name: pyngl
  version: {{ version }}

source:
  url: https://github.com/NCAR/pyngl/archive/{{ version }}.tar.gz
  sha256: e590ae68b4e57658c133f6efbfaab53a0893312ea095cf3f231cf78ab640e71e

build:
  number: 3
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
  host:
    - ncl
    - python
    - numpy
    - libpng
    - fontconfig
    - freetype
    - expat
    - cairo  # [linux]
    - zlib
  run:
    - ncl
    - python
    - {{ pin_compatible('numpy') }}
    - libpng
    - fontconfig
    - freetype
    - expat
    - cairo  # [linux]
    - zlib

test:
  source_files:
    - examples
  requires:
    - nose
  imports:
    - Ngl
  commands:
    - cd examples && for file in xy2.py; do echo $file ; nosetests $file ; done | tee pyngl-test.log

about:
  home: http://pyngl.ucar.edu/
  license: 'PyNGL Source Code'
  summary: 'PyNGL is a scientific data visualization package with an emphasis on high quality 2D visualizations.'

extra:
  recipe-maintainers:
    - khallock
    - marylhaley
    - david-ian-brown
