travis:
  secure:
    BINSTAR_TOKEN: X2jpv5ZF2hDEhbadze3QY1x0CB2qp14yCBz1gkodCo2+OrSF0e0h4EBrCp4uuz0AEEGrundyzx4fFVkxepsbMXJSIuvVcVrq8gNAZHA28Ywkczq3tSTXXapck4GhrOdGhNeM5gzbcOrQa9SNmqS2kSZOuq4JEgUbL7sn89jUn8vy7/8oTLs+1BdMzoCWhQqKmxAqNWpFDHdpzisXO9X1NuKM8k5zKpngXYs7o5GPwugEpqh7WwAx5r4oSqwEutxYvQdZKlfkGTrFLJLqboD7L8R3R7yIufNGTNXp2bXgE3pfQqsBzd5TiuyckV2Ai7rx83uhiSuzTOzuPdg3glMGUln9ndSERutPC5AtTc0UaHpo/ALP1unj0wLU6ay7gzbnkzN/61loefXssvbZlkxn4PLLsmN+UKT2b46ffBxHro/ye3wW7WYLrEZQ+hN8ABzqgkP+3MCZ4SuEkVjZkmn+YDVsPuiCNPmrluB/MkkkysPXKSbnIUBuVDdNzFoMlye5gh69ZLbA3u5n0URnGa2eBpgo5csiDmzadgQaLtfSmutTn05Ym2178IBeaENC1VLMlei6mqFS12nPXUw0aMrDqswdxLOZ+GtjAVlf00QwNvrmHTL8VfuKZVWdguSrOzlNy0l7C6+YXUSHuZqaHdNi9222PWw90rEUe0uY3o4zjJ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
